"""
Django settings for Proyecto project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e^so1o-@k##34g=mxfxa(xbdge$_0!b$mqf&k_6---ty@r-4hy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DUCTO_SQL_SERVER = os.getenv("DUCTO_SQL_SERVER", "")
DUCTO_SQL_DB = os.getenv("DUCTO_SQL_DB", "")
DUCTO_SQL_USER = os.getenv("DUCTO_SQL_USER", "")
DUCTO_SQL_PASSWORD = os.getenv("DUCTO_SQL_PASSWORD", "")
DUCTO_SQL_DRIVER = os.getenv("DUCTO_SQL_DRIVER", "ODBC Driver 17 for SQL Server")
DUCTO_SQL_ENCRYPT = os.getenv("DUCTO_SQL_ENCRYPT", "no")
DUCTO_SQL_TRUST_CERT = os.getenv("DUCTO_SQL_TRUST_CERT", "yes")




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'Vacation',
    'Accounts',
    'seguimiento',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Proyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME': 'project',               # Nombre exacto de tu BD
#         'USER': 'ducto_user',
#         'PASSWORD': 'sqL_2025!###',
#         'HOST': '72.60.59.142',
#         'PORT': '1433',

#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',
#             'trustServerCertificate': 'yes',   # Evita error SSL
#             'MARS_Connection': True,           # Recomendado para Django ORM
#             'schema': 'ducto',
#         },
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": DUCTO_SQL_DB,
        "USER": DUCTO_SQL_USER,
        "PASSWORD": DUCTO_SQL_PASSWORD,
        "HOST": DUCTO_SQL_SERVER,
        "PORT": "",
        "OPTIONS": {
            "driver": DUCTO_SQL_DRIVER,
            "extra_params": f"Encrypt={DUCTO_SQL_ENCRYPT};TrustServerCertificate={DUCTO_SQL_TRUST_CERT};",
            "connection_timeout": 30,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/




