# Generated by Django 3.0.6 on 2023-06-12 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vacation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovac',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feccon', models.DateField()),
                ('dias_totales', models.IntegerField()),
                ('dias_tomados', models.IntegerField()),
                ('dias_pendientes', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
