# Generated by Django 3.0.6 on 2023-06-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0002_auto_20230612_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['usuario'], 'verbose_name': 'Registro de Personas', 'verbose_name_plural': 'Registros de Personas'},
        ),
        migrations.AlterModelTable(
            name='persona',
            table='Persona',
        ),
    ]
