# Generated by Django 3.0.6 on 2023-06-12 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vacation', '0003_auto_20230612_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dias_pendientes',
            field=models.IntegerField(blank=True, verbose_name='Días pendientes'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dias_tomados',
            field=models.IntegerField(blank=True, verbose_name='Total días Utilizados'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dias_totales',
            field=models.IntegerField(blank=True, verbose_name='Total días desde Contrato'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrovac',
            name='duracion',
            field=models.IntegerField(verbose_name='Días hábiles de vacaciones'),
        ),
        migrations.AlterField(
            model_name='registrovac',
            name='fecfin',
            field=models.DateField(verbose_name='Hasta fecha'),
        ),
        migrations.AlterField(
            model_name='registrovac',
            name='fecini',
            field=models.DateField(verbose_name='Desde fecha'),
        ),
    ]
