# Generated by Django 3.0.6 on 2023-06-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0004_auto_20230612_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='dias_pendientes',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='dias_tomados',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='dias_totales',
        ),
    ]
