# Generated by Django 3.0.6 on 2023-06-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0005_auto_20230612_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['usuario_id'], 'verbose_name': 'Registro de Personas', 'verbose_name_plural': 'Registros de Personas'},
        ),
        migrations.AlterModelOptions(
            name='registrovac',
            options={'ordering': ['usuario_id'], 'verbose_name': 'Registro de Vacaciones', 'verbose_name_plural': 'Registros de Vacaciones'},
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.RenameField(
            model_name='registrovac',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
