# Generated by Django 3.0.6 on 2023-06-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0006_auto_20230612_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrovac',
            old_name='duracion',
            new_name='dias_vacaciones',
        ),
        migrations.AddField(
            model_name='persona',
            name='suma_dias_vacaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
