# Generated by Django 3.0.6 on 2023-06-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0007_auto_20230612_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dias_pendientes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
