# Generated by Django 3.0.6 on 2023-06-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0008_persona_dias_pendientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dias_totales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
