# Generated by Django 3.0.6 on 2023-06-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0009_persona_dias_totales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['user_per'], 'verbose_name': 'Registro de Personas', 'verbose_name_plural': 'Registros de Personas'},
        ),
        migrations.AlterModelOptions(
            name='registrovac',
            options={'ordering': ['user_vac'], 'verbose_name': 'Registro de Vacaciones', 'verbose_name_plural': 'Registros de Vacaciones'},
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='usuario_id',
            new_name='user_per',
        ),
        migrations.RenameField(
            model_name='registrovac',
            old_name='usuario_id',
            new_name='user_vac',
        ),
    ]
