# Generated by Django 3.0.6 on 2023-06-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0010_auto_20230613_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovac',
            name='user_vac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacation.Persona'),
        ),
    ]
