# Generated by Django 3.0.6 on 2023-06-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0011_auto_20230613_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['user_per'], 'verbose_name': 'Registro de Persona', 'verbose_name_plural': 'Registros de Personas'},
        ),
    ]
