# Generated by Django 3.0.6 on 2023-06-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0012_auto_20230613_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrovac',
            options={'ordering': ['user_vac', 'fecini'], 'verbose_name': 'Registro de Vacaciones', 'verbose_name_plural': 'Registros de Vacaciones'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='dias_pendientes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dias_totales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='suma_dias_vacaciones',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrovac',
            name='dias_vacaciones',
            field=models.FloatField(verbose_name='Días hábiles de vacaciones'),
        ),
    ]
