# Generated by Django 3.0.6 on 2023-11-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0013_auto_20230614_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='meses_totales',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
