# Generated by Django 2.1.15 on 2025-11-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0014_persona_meses_totales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovac',
            name='fecfin',
            field=models.DateField(verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='registrovac',
            name='fecini',
            field=models.DateField(verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='registrovac',
            name='user_vac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacation.Persona', verbose_name='Usuario'),
        ),
    ]
