# Generated by Django 5.0.14 on 2026-03-08 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0015_auto_20251122_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False, 'ordering': ['user_per'], 'verbose_name': 'Registro de Persona', 'verbose_name_plural': 'Registros de Personas'},
        ),
        migrations.AlterModelOptions(
            name='registrovac',
            options={'managed': False, 'ordering': ['user_vac', 'fecini'], 'verbose_name': 'Registro de Vacaciones', 'verbose_name_plural': 'Registros de Vacaciones'},
        ),
    ]
