# Generated by Django 5.0.14 on 2026-04-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacation', '0016_alter_persona_options_alter_registrovac_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='[project].[ducto].[Persona]',
        ),
        migrations.AlterModelTable(
            name='registrovac',
            table='[project].[ducto].[Registrovac]',
        ),
    ]
