# Generated by Django 5.0.14 on 2026-03-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='IdCliente', primary_key=True, serialize=False)),
                ('rut', models.DecimalField(blank=True, db_column='Rut', decimal_places=0, max_digits=10, null=True)),
                ('dvrut', models.CharField(blank=True, db_column='DVrut', max_length=1, null=True)),
                ('razonsocial', models.CharField(blank=True, db_column='RazonSocial', max_length=80, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=200, null=True)),
                ('horariollamada', models.CharField(blank=True, db_column='HorarioLlamada', max_length=200, null=True)),
                ('direcfactura', models.CharField(blank=True, db_column='DirecFactura', max_length=200, null=True)),
                ('horariorecep', models.CharField(blank=True, db_column='HorarioRecep', max_length=200, null=True)),
                ('direcretiroch', models.CharField(blank=True, db_column='DirecRetiroCH', max_length=200, null=True)),
                ('horarioretiroch', models.CharField(blank=True, db_column='HorarioRetiroCH', max_length=200, null=True)),
                ('comentario', models.TextField(blank=True, db_column='Comentario', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=1, null=True)),
                ('esprincipal', models.BooleanField(blank=True, db_column='EsPrincipal', null=True)),
                ('insercion', models.DateTimeField(db_column='Insercion')),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteCategoria',
            fields=[
                ('idclientecat', models.AutoField(db_column='IdClienteCAT', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cliente_Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientecontacto',
            fields=[
                ('idcontacto', models.AutoField(db_column='IdContacto', primary_key=True, serialize=False)),
                ('tipocontacto', models.CharField(db_column='TipoContacto', max_length=1)),
                ('nombrecontacto', models.CharField(blank=True, db_column='NombreContacto', max_length=80, null=True)),
                ('cargo', models.CharField(blank=True, db_column='Cargo', max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='eMail', max_length=80, null=True)),
                ('fecharegistro', models.DateTimeField(db_column='FechaRegistro')),
            ],
            options={
                'db_table': 'Cliente_Contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('idcotizacion', models.AutoField(db_column='IdCotizacion', primary_key=True, serialize=False)),
                ('numcotizacion', models.DecimalField(blank=True, db_column='NumCotizacion', decimal_places=0, max_digits=10, null=True)),
                ('numcorr', models.IntegerField(blank=True, db_column='NumCorr', null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('nombreproyecto', models.CharField(blank=True, db_column='NombreProyecto', max_length=100, null=True)),
                ('dirproyecto', models.CharField(blank=True, db_column='DirProyecto', max_length=80, null=True)),
                ('codregion', models.IntegerField(blank=True, db_column='CodRegion', null=True)),
                ('destino', models.CharField(blank=True, db_column='Destino', max_length=80, null=True)),
                ('pisos', models.CharField(blank=True, db_column='Pisos', max_length=50, null=True)),
                ('edificios', models.IntegerField(blank=True, db_column='Edificios', null=True)),
                ('valortotal', models.FloatField(blank=True, db_column='ValorTotal', null=True)),
                ('moneda', models.CharField(blank=True, db_column='Moneda', max_length=2, null=True)),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
                ('idusuario', models.CharField(blank=True, db_column='IdUsuario', max_length=15, null=True)),
                ('fechaact', models.DateTimeField(blank=True, db_column='FechaACT', null=True)),
                ('esactiva', models.BooleanField(blank=True, db_column='EsActiva', null=True)),
                ('fechaaceptacion', models.DateField(blank=True, db_column='FechaAceptacion', null=True)),
                ('mt2', models.IntegerField(blank=True, db_column='Mt2', null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='FechaRegistro', null=True)),
            ],
            options={
                'db_table': 'Cotizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T_Categoria',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCat', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'T_Categoria',
                'ordering': ['NombreCat'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tcomppago',
            fields=[
                ('idcomppago', models.AutoField(db_column='IdCompPago', primary_key=True, serialize=False)),
                ('descrip', models.CharField(blank=True, db_column='Descrip', max_length=100, null=True)),
            ],
            options={
                'db_table': 'T_CompPago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testadocliente',
            fields=[
                ('idestadocliente', models.AutoField(db_column='IdEstadoCliente', primary_key=True, serialize=False)),
                ('descrip', models.CharField(blank=True, db_column='Descrip', max_length=100, null=True)),
            ],
            options={
                'db_table': 'T_EstadoCliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('idtipoentrega', models.AutoField(db_column='IdTipoEntrega', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=50, null=True)),
                ('factorTiempo', models.FloatField(db_column='FactorTiempo')),
            ],
            options={
                'db_table': '[ducto].[T_TipoEntrega]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tregion',
            fields=[
                ('codregion', models.IntegerField(db_column='CodRegion', primary_key=True, serialize=False)),
                ('descrip', models.CharField(blank=True, db_column='Descrip', max_length=50, null=True)),
                ('valor', models.IntegerField(db_column='Valor', null=True)),
                ('orden', models.IntegerField(db_column='Orden', null=True)),
            ],
            options={
                'db_table': 'tRegion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='estadoproyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'Estadoproyecto',
            },
        ),
    ]
