# Generated by Django 5.0.14 on 2026-03-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idproyecto', models.DecimalField(db_column='IdProyecto', decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fechacreacion', models.DateField(blank=True, db_column='FechaCreacion', null=True)),
                ('fpago', models.CharField(blank=True, db_column='FPago', max_length=250, null=True)),
                ('valor', models.FloatField(blank=True, db_column='Valor', null=True)),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
                ('numconf', models.CharField(blank=True, db_column='NumCONF', max_length=50, null=True)),
                ('medioconf', models.CharField(blank=True, db_column='MedioCONF', max_length=80, null=True)),
                ('fechaconf', models.DateField(blank=True, db_column='FechaCONF', null=True)),
                ('fechaprimereenvio', models.DateField(blank=True, db_column='FechaPrimerEnvio', null=True)),
                ('fechaact', models.DateField(blank=True, db_column='FechaACT', null=True)),
                ('quienadjudica', models.CharField(blank=True, db_column='QuienAdjudica', max_length=80, null=True)),
                ('emailadjudicacion', models.CharField(blank=True, db_column='eMailAdjudicacion', max_length=80, null=True)),
                ('fechaadjudicacion', models.DateField(blank=True, db_column='FechaAdjudicacion', null=True)),
                ('conhes', models.CharField(blank=True, db_column='ConHES', max_length=1, null=True)),
                ('coneepp', models.CharField(blank=True, db_column='ConEEPP', max_length=1, null=True)),
                ('conotro', models.CharField(blank=True, db_column='ConOtro', max_length=1, null=True)),
                ('fechaheseepp', models.DateField(blank=True, db_column='FechaHESEEPP', null=True)),
                ('moneda', models.CharField(blank=True, db_column='Moneda', max_length=2, null=True)),
                ('fechaingresoseremi', models.DateField(blank=True, db_column='FechaIngresoSEREMI', null=True)),
                ('fechaaprobseremi', models.DateField(blank=True, db_column='FechaAprobSEREMI', null=True)),
                ('fechaultseg', models.DateField(blank=True, db_column='FechaUltSeg', null=True)),
                ('emailcontactofacturacion', models.CharField(blank=True, db_column='eMailContactoFacturacion', max_length=80, null=True)),
                ('fecharegistrocontacto', models.DateTimeField(blank=True, db_column='fecharegistrocontacto', null=True)),
                ('emailenviovistobueno', models.DateField(blank=True, db_column='eMailEnvioVistoBueno', null=True)),
                ('incobrable', models.BooleanField(blank=True, db_column='Incobrable', null=True)),
                ('seg_ingreso_seremi', models.BooleanField(blank=True, db_column='Seg_Ingreso_Seremi', null=True)),
                ('emailsegingresoseremi', models.DateField(blank=True, db_column='eMailSegIngresoSeremi', null=True)),
                ('emailsegentregav00', models.DateField(blank=True, db_column='eMailSegEntregaV00', null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='FechaRegistro', null=True)),
                ('propietario', models.CharField(blank=True, db_column='Propietario', max_length=100, null=True)),
                ('rutpropietario', models.CharField(blank=True, db_column='RutPropietario', max_length=13, null=True)),
                ('idoperador', models.CharField(blank=True, db_column='IdOperador', max_length=15, null=True)),
                ('transferarancel', models.CharField(blank=True, db_column='TransferArancel', max_length=50, null=True)),
                ('arancel', models.FloatField(blank=True, db_column='Arancel', null=True)),
                ('ntramiteseremi', models.CharField(blank=True, db_column='NTramiteSeremi', max_length=50, null=True)),
                ('fechasolacreditacion', models.DateField(blank=True, db_column='FechaSolAcreditacion', null=True)),
                ('fechasolingreso', models.DateField(blank=True, db_column='FechaSolIngreso', null=True)),
                ('fechacargaexp', models.DateField(blank=True, db_column='FechaCargaExp', null=True)),
                ('fechapagoarancel', models.DateField(blank=True, db_column='FechaPagoArancel', null=True)),
                ('fechaingresotimbraje', models.DateField(blank=True, db_column='FechaIngresoTimbraje', null=True)),
                ('fechaaprobtimbraje', models.DateField(blank=True, db_column='FechaAprobTimbraje', null=True)),
                ('nombrereplegal', models.CharField(blank=True, db_column='NombreRepLegal', max_length=80, null=True)),
                ('rutreplegal', models.CharField(blank=True, db_column='RutRepLegal', max_length=13, null=True)),
                ('correo_res_1378_enviado', models.BooleanField(blank=True, db_column='correo_res_1378_enviado', null=True)),
                ('correo_res_1378_fecha', models.DateTimeField(blank=True, db_column='correo_res_1378_fecha', null=True)),
                ('avisomasivo_seremi_enviado', models.BooleanField(blank=True, db_column='avisomasivo_seremi_enviado', null=True)),
                ('avisomasivo_seremi_fecha', models.DateTimeField(blank=True, db_column='avisomasivo_seremi_fecha', null=True)),
            ],
            options={
                'db_table': 'Proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TDuracionProyecto',
            fields=[
                ('idtamano', models.AutoField(db_column='IdTamano', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
                ('duracionhoras', models.FloatField(blank=True, db_column='DuracionHoras', null=True)),
            ],
            options={
                'db_table': '[ducto].[T_DuracionProyecto]',
                'managed': False,
            },
        ),
    ]
