# Generated by Django 5.0.14 on 2026-03-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_proyecto_tduracionproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoproyecto',
            name='forcolor',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
