# Generated by Django 5.0.14 on 2026-03-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_estadoproyecto_forcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duracionproyecto',
            fields=[
                ('idtamano', models.AutoField(db_column='IdTamano', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True)),
                ('duracionhoras', models.IntegerField(blank=True, db_column='DuracionHoras', null=True)),
            ],
            options={
                'db_table': '[ducto].[T_DuracionProyecto]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntregaProyecto',
            fields=[
                ('identrega', models.AutoField(db_column='IdEntrega', primary_key=True, serialize=False)),
                ('rutusercreador', models.CharField(blank=True, db_column='RutUserCreador', max_length=256, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='FechaCreacion', null=True)),
                ('fechacalendario', models.DateTimeField(blank=True, db_column='FechaCalendario', null=True)),
                ('fechaentrega', models.DateField(blank=True, db_column='FechaEntrega', null=True)),
                ('horaentrega', models.CharField(blank=True, db_column='HoraEntrega', max_length=50, null=True)),
                ('plazoestdesarrollo', models.CharField(blank=True, db_column='PlazoEstDesarrollo', max_length=50, null=True)),
                ('rutuserdesa1', models.CharField(blank=True, db_column='RutUserDesa1', max_length=256, null=True)),
                ('fechaasigdesa1', models.DateTimeField(blank=True, db_column='FechaAsigDesa1', null=True)),
                ('rutuserdesa2', models.CharField(blank=True, db_column='RutUserDesa2', max_length=256, null=True)),
                ('fechaasigdesa2', models.DateTimeField(blank=True, db_column='FechaAsigDesa2', null=True)),
                ('rutuserrev1', models.CharField(blank=True, db_column='RutUserRev1', max_length=256, null=True)),
                ('fechaasigrev1', models.DateTimeField(blank=True, db_column='FechaAsigRev1', null=True)),
                ('rutuserrev2', models.CharField(blank=True, db_column='RutUserRev2', max_length=256, null=True)),
                ('fechaasigrev2', models.DateTimeField(blank=True, db_column='FechaAsigRev2', null=True)),
                ('rutuserdesa3', models.CharField(blank=True, db_column='RutUserDesa3', max_length=256, null=True)),
                ('fechaasigdesa3', models.DateTimeField(blank=True, db_column='FechaAsigDesa3', null=True)),
                ('rutuserrev3', models.CharField(blank=True, db_column='RutUserRev3', max_length=256, null=True)),
                ('fechaasigrev3', models.DateTimeField(blank=True, db_column='FechaAsigRev3', null=True)),
                ('rutuserupdate', models.CharField(blank=True, db_column='RutUserUpdate', max_length=256, null=True)),
                ('fechaupdate', models.DateTimeField(blank=True, db_column='FechaUpdate', null=True)),
                ('rutuseranula', models.CharField(blank=True, db_column='RutUserAnula', max_length=256, null=True)),
                ('fechaanulacion', models.DateTimeField(blank=True, db_column='FechaAnulacion', null=True)),
            ],
            options={
                'db_table': '[ducto].[EntregaProyecto]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadoentrega',
            fields=[
                ('idestadoentrega', models.AutoField(db_column='IdEstadoEntrega', primary_key=True, serialize=False)),
                ('descrip', models.CharField(blank=True, db_column='Descrip', max_length=100, null=True)),
            ],
            options={
                'db_table': '[ducto].T_EstadosEntrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tusuario',
            fields=[
                ('idusuario', models.CharField(db_column='IdUsuario', max_length=15, primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(blank=True, db_column='NombreUsuario', max_length=80, null=True)),
                ('idperfil', models.IntegerField(blank=True, db_column='IdPerfil', null=True)),
                ('usrclave', models.CharField(blank=True, db_column='usr_clave', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=1, null=True)),
                ('operador', models.BooleanField(blank=True, db_column='Operador', null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tUsuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Urgencia',
            fields=[
                ('idurgencia', models.AutoField(db_column='IdUrgencia', primary_key=True, serialize=False)),
                ('descrip', models.CharField(blank=True, db_column='Descrip', max_length=50, null=True)),
                ('simbolo', models.CharField(blank=True, db_column='Simbolo', max_length=1, null=True)),
            ],
            options={
                'db_table': '[ducto].[T_Urgencias]',
                'managed': False,
            },
        ),
    ]
