# Generated by Django 5.0.14 on 2026-03-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_duracionproyecto_entregaproyecto_estadoentrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(db_column='IdCalificaciones', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Descripcion', max_length=100)),
            ],
            options={
                'db_table': '[ducto].[T_Calificaciones]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entregaobservacion',
            fields=[
                ('id', models.AutoField(db_column='IdObservEntrega', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True, db_column='Fecha')),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': '[ducto].[Entrega_Observacion]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(db_column='IdObservacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Descrip', max_length=300, null=True)),
            ],
            options={
                'db_table': '[ducto].[T_Observaciones]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoobservacion',
            fields=[
                ('id', models.AutoField(db_column='IdTipoObservacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': '[ducto].[T_TipoObservacion]',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='estadoentrega',
            table='[ducto].[T_EstadosEntrega]',
        ),
    ]
