# Generated by Django 5.0.14 on 2026-04-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0006_destinocotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspNetUser',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=128, primary_key=True, serialize=False)),
                ('nombrecompleto', models.TextField(blank=True, db_column='NombreCompleto', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=256, null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=256, null=True)),
            ],
            options={
                'db_table': 'AspNetUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteAgenda',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=100, null=True)),
                ('descrip', models.CharField(blank=True, db_column='Descrip', max_length=200, null=True)),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Cliente_Agenda',
                'ordering': ['-fecha', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteSeg',
            fields=[
                ('idsegcliente', models.AutoField(db_column='IdSegCliente', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('iduser', models.CharField(blank=True, db_column='IdUser', max_length=128, null=True)),
                ('nota', models.CharField(blank=True, db_column='Nota', max_length=300, null=True)),
            ],
            options={
                'db_table': 'Cliente_Seg',
                'ordering': ['-fecha', '-idsegcliente'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entregaevento',
            fields=[
                ('identregaevento', models.AutoField(db_column='IdEntregaEvento', primary_key=True, serialize=False)),
                ('rutorigen', models.CharField(blank=True, db_column='RutOrigen', max_length=12, null=True)),
                ('rutdestino', models.CharField(blank=True, db_column='RutDestino', max_length=12, null=True)),
                ('fechahora', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '[ducto].[EntregaEvento]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoevento',
            fields=[
                ('idtipoevento', models.AutoField(db_column='IdTipoEvento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Evento', max_length=50, null=True)),
            ],
            options={
                'db_table': '[ducto].[T_TipoEvento]',
                'managed': False,
            },
        ),
    ]
