# Generated by Django 5.0.14 on 2026-04-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0011_add_pk_cotizacion_fpago'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionFpago',
            fields=[
                ('idcotizacionfpago', models.AutoField(primary_key=True, serialize=False)),
                ('linea', models.IntegerField(db_column='Linea')),
                ('concepto', models.TextField(db_column='Concepto')),
            ],
            options={
                'db_table': 'Cotizacion_FPago',
                'ordering': ['linea'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotizacionNota',
            fields=[
                ('idcotizacionnota', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cotizacion_Notas',
                'ordering': ['idcotizacionnota'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotizacionValor',
            fields=[
                ('idcotizacionvalor', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(db_column='Item')),
                ('glosa', models.CharField(db_column='Glosa', max_length=255)),
                ('valor', models.DecimalField(blank=True, db_column='Valor', decimal_places=2, max_digits=18, null=True)),
                ('opcional', models.CharField(blank=True, db_column='Opcional', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Cotizacion_Valor',
                'ordering': ['item'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaCotizacion',
            fields=[
                ('idnota', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.TextField()),
            ],
            options={
                'db_table': 'tNotas',
                'ordering': ['idnota'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TFpago',
            fields=[
                ('idfpago', models.AutoField(db_column='IdFpago', primary_key=True, serialize=False)),
                ('concepto', models.CharField(db_column='Concepto', max_length=255)),
                ('regionrm', models.IntegerField(blank=True, db_column='RegionRM', null=True)),
            ],
            options={
                'db_table': 'tFpago',
                'ordering': ['concepto'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='destinocotizacion',
            options={'managed': False, 'ordering': ['iddestino']},
        ),
        migrations.AlterModelOptions(
            name='itemcotizacion',
            options={'managed': False, 'ordering': ['iditem']},
        ),
        migrations.AlterModelOptions(
            name='monedacotizacion',
            options={'managed': False, 'ordering': ['idmoneda']},
        ),
    ]
