# Generated by Django 5.0.14 on 2026-04-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0013_add_pk_cotizacion_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadocotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Estadocotizacion',
            },
        ),
        migrations.CreateModel(
            name='Estadofactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Estadofactura',
            },
        ),
        migrations.AlterModelOptions(
            name='tfpago',
            options={'managed': False, 'ordering': ['codfp']},
        ),
    ]
